### ISSUE TITLE
Unable to get JMX metrics specific to Snowflake connector

### ISSUE THREAD

**Issue by carao2020** [snowflakedb/snowflake-kafka-connector#447]
Unable to get JMX metrics specific to Snowflake connector. Could you please share the sample JMX configuration for Snowflake connector. I couldnt find this anywhere.

**Comment by sfc-gh-tzhang** [comment]
Would our [online doc ](https://docs.snowflake.com/en/user-guide/kafka-connector-monitor.html#monitoring-the-kafka-connector-using-java-management-extensions-jmx) about JMX help here?

**Comment by carao2020** [comment]
I have tried but it's not working. Could you please share the sample JMX config file. Thanks

**Comment by sfc-gh-japatel** [comment]
Confluent: https://docs.confluent.io/platform/current/installation/docker/operations/monitoring.html

Reference articel: https://docs.datastax.com/en/kafka/doc/kafka/monitoring/kafkaEnableJmx.html

**Comment by carao2020** [comment]
I have tried with below pattern in my JMX config file.
`- pattern: 'snowflake.kafka.connector<connector=(.+), pipe=(.+), category=(.+)><>(.+): (.+)'
  name: snowflake_kafka_connector_$3
  labels:
    connector: "$1"
    pipe: "$2"
    category: "$3"
    "$4": "$5"`

Additionally, PFB the config parameters in my dockerfile.
# Connect JMX config
ENV CONNECT_KAFKA_JMX_PORT=9280
ENV CONNECT_KAFKA_JMX_HOSTNAME=0.0.0.0

ENV KAFKA_JMX_OPTS="-javaagent:/usr/share/java/kafka-connect/jmx_prometheus_javaagent-0.17.0.jar=${CONNECT_KAFKA_JMX_HOSTNAME}:${CONNECT_KAFKA_JMX_PORT}:/opt/optum/jmx-config.yaml -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false"

Still I couldnt find the JMX metrics mentioned as per snowflake documentation. Kindly help if there is any issue in the config.

**Comment by sfc-gh-japatel** [comment]
can you try this:
```
- pattern: snowflake.kafka.connector<connector=(.+), pipe=(.+), category=(.+), name=(.+)><>(.+)
    name: snowflake_kc_$3_$4
    labels:
      connectorName: $1
      pipeName: $2
      category: $3
      metric: $4
    type: GAUGE
```

**Comment by sfc-gh-japatel** [comment]
Also do you use any ui based software like jconsole or visualvm to first identify if such mbeans are reporting the metrics?

**Comment by sfc-gh-japatel** [comment]
https://grafana.com/blog/2020/06/25/monitoring-java-applications-with-the-prometheus-jmx-exporter-and-grafana/

You should be able to go to localhost:<port> for viewing logs if what was exported in jmx (mentioned in above mentioned link)

**Comment by carao2020** [comment]
Hi @sfc-gh-japatel ,

Sorry for late response on this thread. I have tried above config. However, still i am not getting any snowflake specific metrics.

- pattern: "snowflake.kafka.connector<connector=(.+), pipe=(.+), category=(.+), name=(.+)><>(.+)"
  name: snowflake_kc_$3_$4
  labels:
    connector: $1
    pipe: $2
    category: $3
    metric: $4
  type: GAUGE

I dont see any metrics coming out of JMX with prefix snowflake.kafka.connector. However, I see the default metrics from Kafka connector. For example, I am getting below metrics.

kafka_connect_connector_metrics{connector_class="com.snowflake.kafka.connector.SnowflakeSinkConnector",connector="gpt-dv-eligibility-cob-v10-dev",} 1.0
kafka_connect_connector_metrics{connector_version="1.8.1",connector="gpt-dv-eligibility-cob-v10-dev",} 1.0
kafka_connect_connector_metrics{connector_type="sink",connector="gpt-dv-eligibility-cob-v10-dev",} 1.0
kafka_connect_connector_metrics{status="running",connector="gpt-dv-eligibility-cob-v10-dev",} 1.0
kafka_connect_connector_metrics{connector_class="com.snowflake.kafka.connector.SnowflakeSinkConnector",connector="gpt-dv-nwpr-raw-dev",} 1.0
kafka_connect_connector_metrics{connector_version="1.8.1",connector="gpt-dv-nwpr-raw-dev",} 1.0
kafka_connect_connector_metrics{connector_type="sink",connector="gpt-dv-nwpr-raw-dev",} 1.0
kafka_connect_connector_metrics{status="running",connector="gpt-dv-nwpr-raw-dev",} 1.0

These are the configs that i mentioned in my docker build file.

# Connect JMX config
ENV JMX_PORT=9280
ENV KAFKA_JMX_HOSTNAME=127.0.0.1
ENV JMX_OPT=true

ENV KAFKA_JMX_OPTS="-javaagent:/usr/share/java/kafka-connect/jmx_prometheus_javaagent-0.17.2.jar=8085:/opt/optum/jmx-config.yaml -Djava.rmi.server.hostname=${KAFKA_JMX_HOSTNAME} -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9280 -Dcom.sun.management.jmxremote.rmi.port=9280 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"


Kindly review and suggest.

**Comment by sfc-gh-japatel** [comment]
```
lowercaseOutputName: true
rules:
  # Example: snowflake.kafka.connector:connector=SnowflakeSinkConnector_SS_JP_Test,pipe=SNOWFLAKE_KAFKA_CONNECTOR_SnowflakeSinkConnector_SS_JP_Test_PIPE_JUNE_21_SS_LOAD_LOCAL_0,category=file-counts,name=file-count-on-ingestion
  - pattern: 'snowflake.kafka.connector<connector=(.+), pipe=(.+), category=(.+), name=(.+)><>(.+): (.+)'
    name: snowflake_kc_$3_$4_$5
    value: $6
    labels: 
      connectorName: $1
      pipeName: $2
      category: $3
      metric: $5
    type: GAUGE

```

Note the space after comma in pattern line.
