### ISSUE TITLE
Ingestion process is lagging post upgrade Kafka connector to 1.9.2

### ISSUE THREAD

**Issue by sfc-gh-hdogra** [snowflakedb/snowflake-kafka-connector#670]
**[Issue]:** when the connector is upgraded to 1.9.2 the ingestion process is lagging and it has been started from the beginning. The customer wants to have control over the topic from which topic should start ingesting

The  customer is using Snowpipe + Kafka Connector (Note: No Streaming is involved)

Here is the **Kafka config** at the customer's end

```
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: bi-prd
spec:
  configOverrides:
    jvm:
    - -Xmx3500M
    - -Xms3500M
    - -Djava.security.auth.login.config=/etc/kafka-connect/jaas_basic_auth.conf
    server:
    - consumer.client.dns.lookup=use_all_dns_ips
    - producer.client.dns.lookup=use_all_dns_ips
    - rebalance.timeout.ms=120000
    #- connector.client.config.override.policy=All   # custom removal by akragl
    - max.poll.interval.ms=600000
    - consumer.max.poll.interval.ms=600000
    - config.providers = vault,file
    - config.providers.vault.class = com.lululemon.flow.kafka.connect.vault.plugin.VaultConfigProvider
    - rest.extension.classes=org.apache.kafka.connect.rest.basic.auth.extension.BasicAuthSecurityRestExtension
    # - listeners=http://0.0.0.0:9083,https://0.0.0.0:8083 # added to address internal node-to-node comms within the Connect cluster. http can be removed when we fix the cert's SANs.
    # - rest.advertised.listener=http                      # added to address internal node-to-node comms within the Connect cluster. http can be removed when we fix the cert's SANs.
  connectorOverridePolicy: All   # custom addition by akragl
  dependencies:
    interceptor:
      enabled: false
      publishMs: 15000
    kafka:
      authentication:
        #jaasConfig:
        #  secretRef: v2-connect-apikeys
        jaasConfigPassThrough:
          directoryPathInContainer: /vault/secrets
        type: plain
      bootstrapEndpoint: pkc-lz3o7.us-west-2.aws.confluent.cloud:9092
      tls:
        enabled: true
        ignoreTrustStoreConfig: true
    schemaRegistry:
      url: https://psrc-em82q.us-east-2.aws.confluent.cloud
      authentication:
        type: basic
        basic:
          directoryPathInContainer: /vault/secrets/schemaregistry
  enableSchemas: true
  externalAccess:
    loadBalancer:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "kube_namespace=bi-prd,component=connect,lb-scope=all-pods,lll:deployment:environment=prd,lll:business:application-name=Kafka,lll:business:cost-center=0192,lll:business:department=Tech BI Analytics and Integration,lll:business:project-code=1810058822,lll:business:project-name=Global Data Analytics Platform,lll:security:compliance=SOX\\,PII,lll:security:dataclassification=Restricted\\,Internal,lll:business:steward=grp-kafkaplatformall@lululemon.com"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:971948042523:certificate/1861efd6-9c80-437c-90de-c2b90578bc1d
        service.beta.kubernetes.io/load-balancer-source-ranges: 10.0.0.0/8
        #service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        #service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
      domain: aws.lllint.com
      #prefix:
      port: 443 
    type: loadBalancer
  image:
    application: kafka-platform-docker.arti.lululemon.app/lll-cp-kafka-connect:7.3.3-33
    init: kafka-platform-docker.arti.lululemon.app/confluent-init-container:2.5.1
    pullSecretRef:
    #- artifactory-creds   # custom addition by akragl
    - confluent-docker-registry
  internalTopicReplicationFactor: 3   # custom modification (from 1 to 3) by akragl
  keyConverterType: io.confluent.connect.avro.AvroConverter
  valueConverterType: io.confluent.connect.avro.AvroConverter   # moved from the bottom of the spec to here by akragl
  license:                # custom addition by akragl
    globalLicense: true   # custom addition by akragl to reuse operator-defined global license
  metrics:
    prometheus:
      # Reference to some examples:
      # https://github.com/confluentinc/jmx-monitoring-stacks/tree/6.1.0-post/shared-assets/jmx-exporter
      whitelist:
      - "kafka.connect:*"
      - "kafka.producer:*"
      - "kafka.consumer:*"
      rules:
      - pattern: "kafka.connect<type=.*, connector=.*><>status: running"
        value: "1.0"
        valueFactor: "1"
      - pattern: "kafka.connect<type=.*, connector=.*><>status: paused"
        value: "0.5"
        valueFactor: "1"
      - pattern: 'kafka.connect<type=.*, connector=.*><>status: unassigned'
        value: "0.3"
        valueFactor: "1"
      - pattern: 'kafka.connect<type=.*, connector=.*><>status: failed'
        value: "0.0"
        valueFactor: "1"
      - pattern: 'kafka.connect<type=.*, connector=.*><>status: *'
        value: "0.0"
        valueFactor: "1"
      - pattern: 'kafka.(.*)<type=(.*)><>(connector-count|task-count|connector-startup-failure-percentage|task-startup-failure-percentage|offset-commit-failure-percentage)'
        name: "kafka_$1_$2_$3"
        valueFactor: "1"
      - pattern: 'kafka.(.*)<type=(.*), connector=(.*), task=(.*)><>(connector-count|task-count|connector-startup-failure-percentage|task-startup-failure-percentage|offset-commit-failure-percentage|source-record-poll-rate|source-record-active-count-avg|source-record-write-rate|poll-batch-avg-time-ms|source-record-active-count|sink-record-read-rate|sink-record-active-count-avg|sink-record-send-rate|offset-commit-skip-rate|sink-record-active-count)'
        name: "kafka_$1_$2_$5"
        valueFactor: "1"
        labels:
          connector: "$3"
          task: "$4"
      - pattern: ".*"
        valueFactor: "1"
  oneReplicaPerNode: true # custom addition by akragl
  podTemplate:
    serviceAccountName: default  # custom modification by akragl back to original value (was vault-auth-svc)
    affinity:
      nodeAffinity: {}
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: type
                operator: In
                values:
                - connect
            namespaces:
            - bi-prd
            topologyKey: topology.kubernetes.io/zone
          weight: 100
    annotations:
      prometheus.io/port: "7778"
      prometheus.io/scrape: "true"
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: "update"
      vault.hashicorp.com/preserve-secret-case: "true"
      #vault.hashicorp.com/agent-inject-secret-creds: ""
      vault.hashicorp.com/auth-path: "auth/kafka-prd-eks-cluster-kubernetes"
      vault.hashicorp.com/role: "app-kafka-prd-eks"
      vault.hashicorp.com/agent-inject-secret-jaas-config: "app-kafka-kv/prod/confluent"
      vault.hashicorp.com/secret-volume-path-jaas-config: "/vault/secrets"
      vault.hashicorp.com/agent-inject-file-jaas-config: "plain-jaas.conf" # this is a mandatory name
      vault.hashicorp.com/agent-inject-template-jaas-config: |
        {{- with secret "app-kafka-kv/prod/confluent" -}}
        sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="{{ index .Data "connect-api-key" }}" password="{{ index .Data "connect-api-secret" }}";
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-schemaregistry-client-basic: "app-kafka-kv/prod/confluent"
      vault.hashicorp.com/secret-volume-path-schemaregistry-client-basic: "/vault/secrets/schemaregistry"
      vault.hashicorp.com/agent-inject-file-schemaregistry-client-basic: "basic.txt" # this is a mandatory name
      vault.hashicorp.com/agent-inject-template-schemaregistry-client-basic: |
        {{- with secret "app-kafka-kv/prod/confluent" -}}
        username={{ index .Data "ccloud-sr-api-key" }}
        password={{ index .Data "ccloud-sr-api-secret" }}
        {{- end }}
      vault.hashicorp.com/agent-inject-secret-basic-auth-secret: "basicauth"
      vault.hashicorp.com/secret-volume-path-basic-auth-secret: "/vault/secrets/basicauth"
      vault.hashicorp.com/agent-inject-file-basic-auth-secret: "basicauth.secret" # this is a mandatory name
      vault.hashicorp.com/agent-inject-template-basic-auth-secret: |
        {{- with secret "app-kafka2-kv/bi/readwrite/prd/connect" -}}
        {{ index .Data.data "prd-key" }}:{{ index .Data.data "prd-secret" }}
        {{ end }}
        {{- with secret "app-kafka2-kv/prd/lenses" -}}
        {{ index .Data.data "basicauth-key" }}:{{ index .Data.data "basicauth-secret" }}
        {{- end }}
# Removed duplicate license key on pod, we used operator created license.txt, /mnt/secrets/internal-confluent-operator-licensing/license.txt
      # vault.hashicorp.com/agent-inject-secret-license: "app-kafka-kv/prod/confluent"
      # vault.hashicorp.com/secret-volume-path-license: "/vault/secrets"
      # vault.hashicorp.com/agent-inject-file-license: "license.txt" # this is a mandatory name
      # vault.hashicorp.com/agent-inject-template-license: |
      #   {{- with secret "app-kafka-kv/prod/confluent" -}}
      #   {{ index .Data "cfk-license" | base64Decode }}
      #   {{- end }}
    labels:
      lll.deployment.environment: "prd"
      lll.business.application-name: "Kafka"
      lll.business.cost-center: "0192"
      lll.business.department: "Tech_BI_Analytics_and_Integration"
      lll.business.project-code: "1810058822"
      lll.business.project-name: "Global_Data_Analytics_Platform"
      lll.security.compliance: "SOX_PII"
      lll.security.dataclassification: "Restricted_Internal"
      lll.business.steward: "grpkafkaplatformall_at_lululemon.com"
    podSecurityContext:
      fsGroup: 1000
      #runAsGroup: 0
      runAsNonRoot: true
      runAsUser: 1000
    probe:
      liveness:
        initialDelaySeconds: 60
        timeoutSeconds: 20
      readiness:
        initialDelaySeconds: 60
        timeoutSeconds: 20
    resources:
      limits:
        cpu: 900m
        memory: 4500Mi
      requests:
        cpu: 900m
        memory: 4500Mi
    terminationGracePeriodSeconds: 30
  replicas: 4
  telemetry: {}
  tls:
    #directoryPathInContainer: /vault/sslcerts
    jksPassword:
      #secretRef: v2-connect-apikeys
      secretRef: cfk-sslcerts
    secretRef: cfk-sslcerts
status:
  replicas: 0
  restConfig: {}
#license:                                     # custom removal by akragl, since using global license of operator
#  directoryPathInContainer: /vault/secrets   # custom removal by akragl
``` 

**Kafka connector logs** 
[bi-logs.zip](https://github.com/snowflakedb/snowflake-kafka-connector/files/12135820/bi-logs.zip)
