### ISSUE TITLE
SnowflakeJsonConverter converts decimal values to binary hex strings

### ISSUE THREAD

**Issue by sridevs** [snowflakedb/snowflake-kafka-connector#684]
Snowflake Kakfa Connector version - 1.8.2

SnowflakeJsonConverter converts decimal values to binary hex strings. In the below payload, price is "ITQ=" whereas it should be 8.5.

```
{
  "payload": {
    "after": {
      "test_code": "NC0016",
      "test_name": "converter test 6",
      "created_by": "76",
      "created_date": "2023-08-03T01:52:12.03Z",
      "id": 42,
      "last_mod_date": "2023-08-03T01:52:12.03Z",
      "modified_by": "76",
      "price": "ITQ="
    }
```
    
    
 Schema of price field received in the payload for reference
 
```
           {
            "field": "price",
            "name": "org.apache.kafka.connect.data.Decimal",
            "optional": true,
            "parameters": {
              "connect.decimal.precision": "19",
              "scale": "3"
            },
            "type": "bytes",
            "version": 1
          }
```
          
 My config spec
 
```
 spec:
  class: com.snowflake.kafka.connector.SnowflakeSinkConnector
  tasksMax: {{ $snowflakeCommon.tasksMax }}
  config:
    buffer.flush.time: {{ $snowflakeCommon.bufferFlushTime | quote }}
    value.converter: com.snowflake.kafka.connector.records.SnowflakeJsonConverter
    topics: {{ $tableTopicMap.topicName | quote }}
    snowflake.topic2table.map: {{ printf "%s:%s" $tableTopicMap.topicName $tableTopicMap.tableName | quote }}
    snowflake.url.name: {{ $snowflakeCommon.snowflakeUrl | quote }}
    snowflake.database.name: {{ $snowflakeCommon.snowflakeDatabaseName | quote }}
    snowflake.user.name: ${secrets:{{ $release.Namespace }}/{{ $secrets.snowflakeUsername.secretName }}:{{ $secrets.snowflakeUsername.key }}}
    snowflake.private.key: ${secrets:{{ $release.Namespace }}/{{ $secrets.snowflakePrivateKey.secretName }}:{{ $secrets.snowflakePrivateKey.key }}}
    snowflake.private.key.passphrase: ${secrets:{{ $release.Namespace }}/{{ $secrets.snowflakePrivateKeyPassPhrase.secretName }}:{{ $secrets.snowflakePrivateKeyPassPhrase.key }}}
    snowflake.schema.name: {{ $schema | quote }}
    behavior.on.null.values: IGNORE
    errors.retry.timeout: 10 
    errors.retry.delay.max.ms: 180000 
```
    
Looks like kafka has a fix for this - https://issues.apache.org/jira/browse/KAFKA-8595

```
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.decimal.format: NUMERIC
```
But unable to use this. I tried using kafka json converter, but it doesn't work. snowflake sink connector is not using this converter so the cdc doesn't get captured.

Any solution or workaround?
