### ISSUE TITLE
[BUG] Snowpipe Streaming inserting data to different table not as per topic2table.map

### ISSUE THREAD

**Issue by imrohankataria** [snowflakedb/snowflake-kafka-connector#691]
Hi, Im observing very strange behavior I have multiple snowflake sink connectors running that gets data from Eventhub and inserts to Snowflake Tables

What I'm doing - Running Snowflakes sink connectors to insert data to snowflake tables from Eventhub
What is expected - Data to be inserted into Snowflake tables as mapped in snowflake.topic2table.map
What is happening - Data is going to wrong table
Configuration Used - 

Connector 1:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: Connector1
  labels:
    strimzi.io/cluster: sink
spec:
  autoRestart:
    enabled: true
  class: com.snowflake.kafka.connector.SnowflakeSinkConnector
  config:
    buffer.count.records: 10000
    buffer.flush.time: 120
    buffer.size.bytes: 5000000
    snowflake.database.name: DB
    snowflake.ingestion.method: SNOWPIPE_STREAMING
    snowflake.private.key: ${env:SNOWFLAKE_PRIVATEKEY}
    snowflake.private.key.passphrase: ${env:SNOWFLAKE_PASSPHRASE}
    snowflake.role.name: ROLE
    snowflake.schema.name: SCHEMA
    snowflake.topic2table.map: schema.snowflakekafkaconnector:snowflakekafkaconnector
    snowflake.url.name: *******
    snowflake.user.name: ******
    topics: schema.snowflakekafkaconnector
  tasksMax: 1
```

Connector 2
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: Connector2
  labels:
    strimzi.io/cluster: sink
spec:
  autoRestart:
    enabled: true
  class: com.snowflake.kafka.connector.SnowflakeSinkConnector
  config:
    buffer.count.records: 10000
    buffer.flush.time: 120
    buffer.size.bytes: 5000000
    snowflake.database.name: DB
    snowflake.ingestion.method: SNOWPIPE_STREAMING
    snowflake.private.key: ${env:SNOWFLAKE_PRIVATEKEY}
    snowflake.private.key.passphrase: ${env:SNOWFLAKE_PASSPHRASE}
    snowflake.role.name: ROLE
    snowflake.schema.name: SCHEMA
    snowflake.topic2table.map: schema.snowflakekafkaconnectortwo:snowflakekafkaconnectortwo
    snowflake.url.name: *******
    snowflake.user.name: ******
    topics: schema.snowflakekafkaconnectortwo
  tasksMax: 1
```

Even though the connectors are different, and have different/distinguishable source topic and target destination, but still Connector2 is inserting data in Connector1 Mapped table. (Because they look similar?)

How did i resolve?
In Connector2 I added a prefix on target table **snowflakekafkaconnectortwo to ab_snowflakekafkaconnectortwo** and this works. But this is not a clean solution to the problem and I want to mark as a bug.

Im close to PRD Release, and want to see if we can rely on Snowflake Connector in future or not

Thanks
