### ISSUE TITLE
Snowpipe Streaming Duplicate records / Not Exactly Once

### ISSUE THREAD

**Issue by imrohankataria** [snowflakedb/snowflake-kafka-connector#710]
Hi, 

PROD DATA GETTING DUPLICATES!!!

Using Snowflake Sink Connector to get my data from Eventhub to Snowflake, but Im experiencing duplicate records, entire set getting copied again.

Configuration used for Snowflake Sink Connector -
```
spec:
  autoRestart:
    enabled: true
  class: com.snowflake.kafka.connector.SnowflakeSinkConnector
  config:
    buffer.count.records: 10000
    buffer.flush.time: 60
    buffer.size.bytes: 5000000
    snowflake.database.name: DB
    snowflake.ingestion.method: SNOWPIPE_STREAMING
    snowflake.private.key: ${env:KEY}
    snowflake.private.key.passphrase: ${env:KEY}
    snowflake.role.name: ROLE
    snowflake.schema.name: SCHEMA
    snowflake.topic2table.map: 38 TOPICS
    snowflake.url.name:URL
    snowflake.user.name: USER
    topics: 38 TOPICS
  pause: true
  tasksMax: 38
```

Using JDBC Source Connector

<img width="540" alt="image" src="https://github.com/snowflakedb/snowflake-kafka-connector/assets/41874450/3222ec50-b594-4a51-9a91-b33a1df58904">
