### ISSUE TITLE
Sporadic events causing lags?

### ISSUE THREAD

**Issue by SubhraB** [snowflakedb/snowflake-kafka-connector#798]
I have a snowflake connector (using strimzi) defined like below, it consumes from a high traffic volume topic, and I have set a filter (from confluent), that will make the connector consume may be handful of events per day, then may be no events for many days, then there will be one, so events are really sporadic. We are noticing this is causing the lag to grow a lot. Trying to understand whether the issue is from the connector side, the filter or configuration or kafka broker.

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: connect-dev-ext
  name: my-snowflake-sink-connector
spec:
  autoRestart:
    enabled: true
  class: com.snowflake.kafka.connector.SnowflakeSinkConnector
  config:
    buffer.flush.time: 60
    errors.log.enable: true
    errors.log.include.messages: true
    errors.tolerance: all
    key.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    key.ignore: true
    schema.ignore: true
    snowflake.database.name: MY_DB
    snowflake.private.key: '${secrets:strimzi-kafka/snowflake-secrets:privateKey}'
    snowflake.private.key.passphrase: '${secrets:strimzi-kafka/snowflake-secrets:privateKeyPassphrase}'
    snowflake.schema.name: my_schema
    snowflake.topic2table.map: 'my_kafka_topic:my_snowflake_table'
    snowflake.url.name: '${secrets:strimzi-kafka/snowflake-secrets:accountUrl}'
    snowflake.user.name: '${secrets:strimzi-kafka/snowflake-secrets:userName}'
    topics: my_kafka_topic
    transforms: snowflakeFilter
    transforms.snowflakeFilter.filter.condition: '$[?("myValue" in @.my_key)]' //my_key is an array of strings
    transforms.snowflakeFilter.filter.type: include
    transforms.snowflakeFilter.missing.or.null.behavior: exclude
    transforms.snowflakeFilter.type: io.confluent.connect.transforms.Filter$Value
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
  tasksMax: 1
```

We have another snowflake connector without any filter, but on a different topic, that works as expected.
