### ISSUE TITLE
Avro decimal 

### ISSUE THREAD

**Issue by dechants** [snowflakedb/snowflake-kafka-connector#897]
Hi,

I have the following settings (snowflakeinc/snowflake-kafka-connector:2.2.2):

```
class: com.snowflake.kafka.connector.SnowflakeSinkConnector
configs:
  snowflake.ingestion.method: "SNOWPIPE_STREAMING"
  snowflake.enable.schematization: "true"
  value.converter.schemas.enable: "true"
  value.converter: io.confluent.connect.avro.AvroConverter
  value.converter.schema.registry.url: http://schemaregistry.kafka.svc.cluster.local:8081
```

My schema:

```
{
	"type": "record",
	"name": "ConnectDefault",
	"namespace": "io.confluent.connect.avro",
	"fields": [
		{
			"name": "TENANTID",
			"type": [
				"null",
				"string"
			],
			"default": null
		},
		{
			"name": "INCREMENTALKEY",
			"type": {
				"type": "bytes",
				"scale": 0,
				"precision": 19,
				"connect.version": 1,
				"connect.parameters": {
					"scale": "0",
					"connect.decimal.precision": "19"
				},
				"connect.name": "org.apache.kafka.connect.data.Decimal",
				"logicalType": "decimal"
			}
		},
```

The connector creates the table, however `INCREMENTALKEY` is `VARCHAR(16777216)`.

How can I make sure that the connector automatically creates the table in Snowflake and "maps" numeric values correctly?
